Cleaned Footer.jsx and NavbarComponent.jsx file
cs472-team6/cs472-team6 pull request #109
Opened 2023-03-31 23:39 UTC by arroya2

The functionality nor appearances of these two components were changed. However, I did clean the code to make it easier to read and also removed unnecessary code that wasn't needed for the program to work properly.

### NavbarComponent.jsx

- function name was changed from Navbar to NavbarComponent to match file name and adhere code convention
- removed unnecessary code to make file more readable

### Footer.jsx

- removed unnecessary code to make file more readable

2023-04-07 00:10 UTC, Lettuce05 requested changes

2023-04-07 00:10 UTC, Lettuce05 commented on src/components/NavbarComponent/NavbarComponent.jsx
> +                <span>Home</span>
It would be nice if the name of these links were responsive. What if a user doesn't have all the sections or prescribed links that are hard coded here.

2023-04-07 00:10 UTC, Lettuce05 commented on src/components/Footer/Footer.jsx
>                href={linkedIn}
Ideally these links should be dynamic, where the user has the option to change the name of the link or even the number of links. If they are going to be hardcoded I would at least suggest adding an option that if the user left the link option empty then the link would not be rendered at all (let's say they don't have a link/account that associates with the hard coded link name that is provided.

2023-04-07 00:10 UTC, Lettuce05 commented on src/components/faqSection/faqComponent.js
> +import faqSection from "./faqSection";
This fixes the error of the application not being able to run.

2023-04-25 05:38 UTC, arroya2 commented
I fixed the issues that were mentioned by Anthony. Let me know if there is any other things that need to be changed

2023-04-25 06:24 UTC, carruthjhall requested changes
Footer:
+The component is responsive and works in both light and dark mode.
+The options are able to be edited and are reflected in the preview.
+Removing the URL from the options works, and the affected option disappears from the preview as intended.
+Able to get 97% test coverage

-The icons appear in the light mode perfectly, but in the dark mode they blend in. 
This can be fixed by inverting the icon colors depending on what color scheme the user has. You can check the icons in the Contact Section component to see how to do that
Here's what it looks like on Figma: 
![image](https://user-images.githubusercontent.com/85139652/234188792-09f6169b-7e33-4180-846e-c1b42b0e4103.png)
The icons also have a gradient border around them in both the light and dark mode so that's one last thing to add so it'll be perfect  

NavBar:
+The Navbarcomponent function name fix doesn't cause any issues on my end
+The component is responsive, and looks correct in both light and dark mode.
+The options are able to be edited and the changes are reflected in the preview.
+Removing the URLs removes the affected option as intended
+Able to get 97% test coverage

2023-04-26 08:19 UTC, closed without merging