Faq section updates
cs472-team6/cs472-team6 pull request #120
Opened 2023-04-12 06:26 UTC by carruthjhall

This PR fixes some bugs that the faqSection had such as; contact me button not doing anything and accordion overflowing into components below.
### Code Changes
___
- ContactSection.jsx
  - Added an anchor element with the id: 'ContactSection'.
- faqSection.jsx
  - Added an anchor element onto the Contact Me button that will jump to the Contact Section on the page. 
  (If there is one added to the preview panel.)
  - Added a scroll overflow to the question accordion so that the text does not bleed into a component below. 
  (Scrollbar only visible if the text overflows)
     - Small Screen:
![smallscreen](https://user-images.githubusercontent.com/85139652/231368267-1684ff0e-5b6e-4584-9f34-5cba10cecdbb.png)
    - Medium Screen:
![image](https://user-images.githubusercontent.com/85139652/231368567-e8af865c-bd03-44ca-8206-905607522967.png)
    - Large Screen:
![image](https://user-images.githubusercontent.com/85139652/231368482-a213c265-875b-435b-9d8c-4607e8e4c31c.png)
  - Modified some of the div heights to make the scroll not go too far down.
  - Removed unnecessary/unused code.
  - Reformatted the code to use less whitespace.
- Accordion.jsx
  - Made the dropdown arrows extend a little further out on the small screen view
- faqComponent.jsx
  - Fixed the import bug
- faqComponent.test.jsx
  - Fixed the import bug
  - Coverage
![image](https://user-images.githubusercontent.com/85139652/231366608-6035b381-4516-490a-a16d-b47b15be1699.png)
- ContactSection.test.jsx
  - Redid some code due to the addition of the anchor element
  - Coverage
![image](https://user-images.githubusercontent.com/85139652/231366397-fbbcd5dc-262c-4140-af20-249e8ed3d059.png)
-  registeredComponents.jsx
   - Removed the duplicate faqSection component entry.

2023-04-17 22:04 UTC, Lettuce05 requested changes
We do not want to hardcode the functionality of jumping to a contact section. To allow more flexibility I would suggest adding a new component option where the user can set the link for the Contact Me button. 

The addition of the ids on the ContactSection component go against HTML rules and will break functionality. I suggest that these ids are removed and if the above suggested changes are made then the ids will no longer be needed.

2023-04-17 22:04 UTC, Lettuce05 commented on src/components/faqSection/faqSection.jsx
> +                    <a href="#ContactSection">
I would remove this href and add a component option that the user is able to change. Allowing the user to set where they want the button to link to allows for more accessibility. It also makes since with the functionality that is already implemented with the user being able to change the text of the contactBtn.

2023-05-01 00:28 UTC, Lettuce05 requested changes
This component is not responsive. At multiple screen sizes the questions get cut off an the user has to scroll horizontally. I think it would be preferred if the questions simply moved underneath the heading at the sizes where it gets cut off.

![image](https://user-images.githubusercontent.com/61034923/235383474-ecfd7d6c-b309-4fb9-82a9-2bd750dcc5d7.png)


Also there is merge conflicts that must be resolved with this PR.

2023-05-01 02:18 UTC, Lettuce05 approved these changes
Great Work! As seen below the component is responsive for all sizes. Test coverage remains good. 

![image](https://user-images.githubusercontent.com/61034923/235391896-cf7ef33d-621d-4a9d-87c9-655730d3a6a7.png)

![image](https://user-images.githubusercontent.com/61034923/235391939-cc28fcc5-3a41-4f85-9868-846e0368daa9.png)

![image](https://user-images.githubusercontent.com/61034923/235391967-863fd1c2-b922-434b-8c1c-d813000b4866.png)

2023-05-01 03:40 UTC, ebacolod requested changes

2023-05-01 03:40 UTC, ebacolod commented on src/components/faqSection/faqSection.jsx
> +        <div className="flex m-auto md:pl-[30px] md:pr-[80px] pl-2 p-4 pr-[10px] lg:w-[1050px] xl:w-[95%] lg:h-[750px] xl:h-[500px] md:w-[95%] md:h-[800px] w-[390px] h-[775px] flex-col bg-white dark:
The FAQ side follows the width of the screen. 

<img width="655" alt="image" src="https://user-images.githubusercontent.com/58874823/235400379-4f1706f6-8acb-4893-a3ff-c1ba3caacf32.png">

I think the best way to do the responsiveness is to remove the rules `lg:w-[1050px] xl:w-[95%]` and replace it with `xl:w-[1257px]`

2023-05-01 03:40 UTC, ebacolod commented on src/components/ContactSection/ContactSection.jsx
> +            <h2 className={`text-[64px] w-[400px] h-auto text-ellipsis whitespace-pre-wrap text-transparent bg-clip-text bg-gradient-to-r ${gradient} bg-red-400`}>{displayHeader}</h2>
Your display header and description is listed twice

<img width="602" alt="image" src="https://user-images.githubusercontent.com/58874823/235403198-bb4e5c41-92a2-40c5-bfff-2907b16c74a0.png">

2023-05-01 04:02 UTC, carruthjhall commented on src/components/ContactSection/ContactSection.jsx
> +            <h2 className={`text-[64px] w-[400px] h-auto text-ellipsis whitespace-pre-wrap text-transparent bg-clip-text bg-gradient-to-r ${gradient} bg-red-400`}>{displayHeader}</h2>
Fixed the errors and added the suggested width fix

2023-05-01 04:38 UTC, ebacolod approved these changes
The new changes look good. Nice Work!

2023-05-01 04:39 UTC, merged