Add Services Section Component
cs472-team6/cs472-team6 pull request #121
Opened 2023-04-14 05:40 UTC by Lettuce05

This pull request aims to resolve issue #116 . In this pull request I have added the ServicesSection Component, the corresponding ServicesSectionOptions Component, and the corresponding tests.

## New Features

- ServicesSection Component
  - This component will allow the user to add the services they offer to their website
- ServicesSectionOptions Component
  - Allows the user to edit the the rendered instances of the ServicesSection Component

## Screenshots of New Features

### ServicesSection (Light Mode)

![services_section_light](https://user-images.githubusercontent.com/61034923/231947207-f662a773-526f-4a93-9da0-f83be5fc2e58.png)

### ServicesSection (Dark Mode)

![services_section_dark](https://user-images.githubusercontent.com/61034923/231947285-e148924f-2d5d-4523-9c68-e908aa185ff0.png)

### ServicesSectionOptions

![image](https://user-images.githubusercontent.com/61034923/231947400-9b933868-f5c5-4151-8ea7-de38577d3215.png)

### ServicesSection Testing

![services_section_testing](https://user-images.githubusercontent.com/61034923/231947482-814f66d4-d7b7-4369-aca9-aa7dea761c4c.png)

## Code Changes

### src/components/ServicesSection/ServicesSection.jsx

- Added the ServicesSection component (this is the function that is used to render the component in the PreviewPanel)

### src/components/ServicesSection/ServicesSection.test.jsx

- Added tests to provide coverage for everything related to the ServicesSection component
- NOTE: The only thing that is not covered here is the code dealing with the file input button. This cannot be properly be tested since we are not able to render the component in the browser in this test.

### src/components/ServicesSection/ServicesSectionComponent.js

- Added the PageComponent instance of the ServicesSection Component. This registers the ServicesSection component and allows the component to work properly within the application.

### src/components/ServicesSection/ServicesSectionOptions.jsx

- Added the ServicesSectionOptions Component which allows the user to edit the rendered instances of the ServicesSection Component. This options component allows the user to add, delete, and edit services within the rendered instances of the services section. The user also change the heading of the component if they wish the component to be used for something other than services (Allows for more flexibility).

### src/components/ServicesSection/ServicesSectionPreview.png

- This is the preview image that is used in the ComponentsListTab in the SideNav. This allows the user to see what the component will look like before they add it to their website.

### src/index.css

- Added custom styles in order to clean up the styling of option components

### src/utils/registeredComponents.js

- Added the ServicesSection Component to the registeredComponents array

2023-04-19 03:45 UTC, ebacolod requested changes
All the functionality of the component works well. The input gets rendered properly. I like how you can add more services and delete specific ones. The responsiveness also looks clean. I'm able to get the same coverage too.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/58874823/232961203-7988aac6-ad07-4c67-8df4-6a18978bb0a0.png">

I only have one recommendation though. I think it may be better to group the options for each service with the `<details>` tag. My explanation for this is down below. Otherwise, good job!

2023-04-19 03:45 UTC, ebacolod commented on src/components/ServicesSection/ServicesSectionOptions.jsx
> +        <div className="mt-3">
I would recommend a `<details>` tag as opposed to a `<div>`. This would allow the user to group the options together by their service. It would make the list of options more concise and easier to navigate since there's a lot less to scroll through. For the detail summary, I would include the item number as well as the name of the service. I have it like this in my skills component as shown below. This would be nice so that the user can better associate the options with the service on the render page.

<img width="135" alt="image" src="https://user-images.githubusercontent.com/58874823/232959950-9cb71b71-491a-4642-baa3-fd6f807fa876.png">

2023-04-20 21:35 UTC, ebacolod requested changes
<img width="332" alt="image" src="https://user-images.githubusercontent.com/58874823/233491511-1c33eb0c-6f85-4cb0-a366-9e3ca26633ef.png">

<img width="571" alt="image" src="https://user-images.githubusercontent.com/58874823/233491781-27c5fdfc-5b1b-499a-bf79-14bcb267d213.png">


When rechecking your component, I noticed that these two tests failed. I can't tell where the problem is in the code, but it's most likely due to the details tag. You just need to adjust your tests so that it accounts for this.

2023-04-24 17:54 UTC, Lettuce05 commented
Had to close and reopen pull request in order to run GitHub action. Action would not run on preexisting pull requests.

2023-04-24 23:48 UTC, Lettuce05 commented
@ebacolod I have updated the tests to reflect the changes made to the component and everything is passing now.

![services-section-tests](https://user-images.githubusercontent.com/61034923/234139158-07954f16-eb6b-4b51-b435-ec5597fb8dd7.png)

2023-04-25 00:59 UTC, Lettuce05 commented
Made an update to the Vitest GitHub action so closing and reopening to test the new CI/CD workflow

2023-04-25 02:26 UTC, alexfox361 approved these changes
Hey @Lettuce05, I tested this component and all of its features. Everything seems to work great and I like the implementation of adding and removing details. Additionally, the tests work well and everything seems good to go. 

Nice work!

2023-04-25 08:18 UTC, ebacolod approved these changes
Testing looks good now. The functionality of your components works well. I approve! Awesome work!

2023-04-25 15:29 UTC, merged