Added CS (Case Study) Hero component and testing
cs472-team6/cs472-team6 pull request #125
Opened 2023-04-14 09:42 UTC by carruthjhall

This PR request addresses issues #122 & #113 and allows the user to add the Case Study Hero section component to their portfolio. This PR adds the CaseStudyHero component, along with the CaseStudyHeroOptions and testing for the components.

### New Features
___
- CaseStudyHero Component
  - This component allows the user to showcase one of the clients they have done work for.
- CaseStudyHeroOptions Component
  - This allows the user to edit the client/project information, descriptions of the project, as well as an image of the project they worked on.
### Previews
___
### Dark Mode:
![image](https://user-images.githubusercontent.com/85139652/232004293-ca266883-4cd3-4af9-a2d6-c5d2aea1faea.png)
### Light Mode:
![image](https://user-images.githubusercontent.com/85139652/232004924-5b168876-1c35-4d26-a537-cf509f21ddcc.png)
### Options:
![image](https://user-images.githubusercontent.com/85139652/232005166-bc670367-df7c-4a5b-abda-b4005acaf97b.png)
### Responsive Styling
### Medium:
![image](https://user-images.githubusercontent.com/85139652/232005290-0b63bd4e-f269-404a-8cad-c932594d1eed.png)
### Small:
![image](https://user-images.githubusercontent.com/85139652/232005413-60e91257-7b0f-40b4-a078-711661ac183c.png)
### CS Hero Testing
___
![image](https://user-images.githubusercontent.com/85139652/232006483-ccd050ea-b177-43c6-a814-df4a060c1781.png)

### Code Changes
___
- src/components/CaseStudyHero/CaseStudyHero.jsx
  - Added the CSHero Component function to render the component
- src/components/CaseStudyHero/CaseStudyHeroOptions.jsx
  - Added the CSHeroOptions Component function that renders the options to edit the component,
- src/components/CaseStudyHero/CaseStudyHeroComponent.jsx
  - Added the component entry function to add the component to the registeredComponents array.
- src/components/CaseStudyHero/CaseStudyHero.test.jsx
  - Added the testing for the CaseStudyHero component
- src/components/CaseStudyHero/CaseStudyPreview.png
  - Added the preview of the CSHero that is displayed in the list of components
- src/utils/registerComponents.jsx
  - Added the CaseStudyHero component to the registeredComponents array using the correct syntax.

2023-04-19 05:53 UTC, ebacolod requested changes
The input is rendered properly and can be edited. The responsiveness is clean. Running your tests, I'm able to get full coverage. 

<img width="955" alt="image" src="https://user-images.githubusercontent.com/58874823/232977815-f0140847-32cb-47f4-9dfd-79c0091143ea.png">

The only other thing that needs to be addressed is the component's options. More details below. Otherwise, nice work!

2023-04-19 05:53 UTC, ebacolod commented on src/components/CaseStudyHero/CaseStudyHeroOptions.jsx
> +                <summary>Project Information</summary>
Instead of grouping all the text input under one `<detail>` tab, you can group them under two (Header and About Project). In that way, it is better organized. 

The image input can be left out of the two groupings.

Also, when you regroup the Header options, reorder the options for the Project header and the Client info 
so that they're together. So then it would look like:
- Project Task:
- Project Name: (Client Name Header:)
- Client Name:
- Role:
- Location:

2023-04-19 05:53 UTC, ebacolod commented on src/components/CaseStudyHero/CaseStudyHeroOptions.jsx
> +                    <label className="block">Client Name Header:</label>
I think this might be called "Project Name" instead of "Client Name Header". The client name is listed twice, so I think it would be better to call it by a different label

2023-04-19 05:53 UTC, ebacolod commented on src/components/CaseStudyHero/CaseStudyHeroOptions.jsx
> +                    <label className="block" title="Use an image upload site such as imgur.com to showcase your work.">Project Picture(URL):</label>
As mentioned in Discord, using Imgur as a website to host images can break the functionality of the images and doesn't seem to work for the exported site.

You can use the new GitHub repo below to upload images and source them from there:
https://github.com/cs472-team6/cs472-team6-resources

2023-04-20 22:09 UTC, ebacolod approved these changes
I rechecked the options, responsiveness, and testing. All of it looks good. Nice Work!

2023-04-24 17:54 UTC, Lettuce05 commented
Had to close and reopen pull request in order to run GitHub action. Action would not run on preexisting pull requests.

2023-04-25 03:30 UTC, WuliuQ requested changes
The responsiveness is nice, every input from user works fine, but when I run the test, I got this:
![屏幕截图 2023-04-24 202419](https://user-images.githubusercontent.com/94213565/234167283-d8c80a69-7816-474c-a84a-32f135b02e8d.png)
I think the reason is after you change the code, the location of some value also change. I try to change the 5 to 6 in the code "let handleChange = component.toTree().rendered.rendered[5].props.onChange;" and it fix the second error, you may need to find the correct location in the first error to fix it.

2023-04-25 03:32 UTC, Lettuce05 commented
Closing and Reopening so that updated GitHub Action can run.

2023-04-25 15:00 UTC, WuliuQ approved these changes

2023-05-01 02:18 UTC, merged