Update CtaSection/Blog Page Component
cs472-team6/cs472-team6 pull request #130
Opened 2023-04-17 18:12 UTC by WuliuQ

This pull request includes updates for the CtaSection/Blog Page components:

## Code Change

- **BlogPage.jsx BlogPageComponent.js, BlogPageComponent.js, BlogPageOptions.jsx**
   change the variable names on these files to make it more suitable for their role

- **BlogPagePreview.png**
   change the preview of Blog Page component in the sidePanel to show what it actually looks like.
   
   Before:
   ![sd](https://user-images.githubusercontent.com/94213565/232572665-351720e6-0cdb-4335-869c-f003cdda944d.png)
   After:
   ![BlogPagePreview](https://user-images.githubusercontent.com/94213565/232572763-a5111466-8671-4267-b7d3-ec2e238971ab.png)

- **CtaSection.jsx**
  Change margin of the test in large screen size to match what it looks like in the figma.

   Before:
   ![Before](https://user-images.githubusercontent.com/94213565/232573244-4a3ccf48-05ea-4b4e-9011-7249f4360a5f.png)

   After:
   ![after](https://user-images.githubusercontent.com/94213565/232573672-45297e83-4aab-4113-a940-e9f4ed1ad3b3.png)

2023-04-19 23:49 UTC, ebacolod requested changes
I doubled checked inputs, light/dark mode, responsiveness, and testing. I've made a few requests that I think help polish your component.

2023-04-19 23:49 UTC, ebacolod commented on src/components/CtaSection/CtaSection.jsx
> +    <div className={'py-20 px-10 md:px-20 lg:px-40'}>
Both your CtaSection and BlogPage fit the screen size. 
<img width="708" alt="image" src="https://user-images.githubusercontent.com/58874823/233218213-d4ed6558-5f51-4a16-9f5e-514799be41f7.png">

When at very large screen sizes, these components look much larger than other components. This may be a concern since we're presenting on larger screens. For consistency, a max-width should be set. In the Figma file, the largest screen size is 1440px, but the component should not go beyond the max-width.

2023-04-19 23:49 UTC, ebacolod commented on src/components/CtaSection/CtaSection.jsx
>      <div className="font-bold font-baijamjuree
The font type we use for Baijamjuree is `font-main`. The default Baijamjuree font is different from the Baijamjuree from the Figma file. This'll make the components more consistent and well-polished. The default Baijamjuree was used in the BlogPage.jsx file as well, so don't forget to fix it there too.

Default:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/58874823/233219749-c3d0346b-0ccf-4483-9de0-97f69e808019.png">

Figma:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/58874823/233219816-322c5034-631e-4d8f-afd9-8df6a32a3ba5.png">

*Note: the default gradient and fonts are located in the tailwind.config.cjs file

2023-04-19 23:49 UTC, ebacolod commented on src/components/CtaSection/CtaSection.jsx
>          <div className = {`bg-gradient-to-r ${gradient} text-transparent bg-clip-text flex items-center`}>
The arrow doesn't change its gradient.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/58874823/233220754-0c799b3a-b76d-485c-bd78-2348cbd95e45.png">

If you look at Anthony's ServicesSection component (specifically ServicesSection.jsx), he's managed to change the color of the arrow when going to-and-from light and dark mode. You will most likely set the arrow to transparent and set the background to the gradient. But if that doesn't work out, feel free to reach out to the our Discord channel.

Link to ServicesSection component:
https://github.com/cs472-team6/cs472-team6/pull/121 

Link to styling `<svg>` tags with tailwind:
https://tailwindcss.com/docs/stroke

2023-04-20 22:47 UTC, ebacolod requested changes

2023-04-20 22:47 UTC, ebacolod commented on src/components/BlogPage/BlogPage.jsx
> +        <div className={`flex bg-white text-black dark:bg-black dark:text-white py-6 lg:px-[202px] md:px-[80px] lg:max-w-[1036px] md:max-w-[864px] max-w-[340px] mx-auto item-center`}>
When transitioning from medium to large screens, the CtaSection and BlogPage components shrink. (You can see the difference better by opening the images in new tabs and switching between those images.)

Medium Screen [1023px]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/58874823/233500735-f9e027e2-1a69-4920-9430-6966b91ae0cf.png">

Large Screen [1024px]
<img width="538" alt="image" src="https://user-images.githubusercontent.com/58874823/233500820-8b044c89-99ab-4c6a-ba76-4df1ea8376a2.png">

This shrink is because of the `lg:px-[202px]` rule. It's adding a lot of padding to both components. If you delete those rules for both components, it'll look more like the Figma file.

2023-04-20 22:58 UTC, WuliuQ commented on src/components/BlogPage/BlogPage.jsx
> +        <div className={`flex bg-white text-black dark:bg-black dark:text-white py-6 lg:px-[202px] md:px-[80px] lg:max-w-[1036px] md:max-w-[864px] max-w-[340px] mx-auto item-center`}>
Thanks your comment, after I delete those rules, it fix the issue.

2023-04-22 21:25 UTC, ebacolod approved these changes
Thanks for considering my changes. LGTM!

2023-04-24 18:07 UTC, Lettuce05 commented
Had to close and reopen pull request in order to run GitHub action. Action would not run on preexisting pull requests.

2023-04-25 20:12 UTC, Lettuce05 requested changes
Great Work! I think that the updates to both components make their look and functionality much better. I did make a few comments on a couple of improvements that I think should be made as well as a bug that I found and a fix for it. I reran all tests and everything still passes.

2023-04-25 21:28 UTC, WuliuQ commented on src/components/BlogPage/BlogPage.jsx
> +        <div className= "font-normal font-main">
I add the w-full in the div you said, can you test again to see that works?

2023-04-29 13:12 UTC, ZacheryEC001 reviewed
These changes are looking good; however, I am adding dynamic gradient support, and my PR I am submitting in an hour or so fixes the CtaSection icon. The changes made in the CtaSection for the gradient is not required in this PR and I would recommend reverting these changes to prevent merge conflicts.

2023-04-30 04:22 UTC, Lettuce05 requested changes
Your branch currently has merge commits therefore I cannot fully re-review it since the conflicts have to do with a component that is a focus of this PR. Your branch is currently 103 commits behind main, so you definitely want to merge main into your branch to make sure nothing else changed or affected your work.

I will review when main has been merged and merge conflicts have been resolved.

2023-05-01 00:11 UTC, Lettuce05 requested changes
Great work! The component is now completely responsive and all previous bugs have been fixed. All tests pass as seen in the image below. The test coverage for both components is also at 100%.

![image](https://user-images.githubusercontent.com/61034923/235382330-261ebfda-996d-4560-83ba-7d3dd5ca158e.png)

The component is causing build errors I have commented on the line of code that must change in order to fix this problem.

2023-05-01 00:11 UTC, Lettuce05 commented on filesystem.js
> +  ['Blog Page', [
This change is causing errors with the export website process. The entry in the filesystem.js file should match the folder name. The entry in webcontainer/registeredComponents.js should be the name of the component. This is a simple mistake. Please correct the change and try exporting your website with your component to make sure that there is no export errors.

2023-05-01 00:37 UTC, Lettuce05 requested changes
You have fixed the filesystem.js file however since the names (strings) in the registeredComponents.js and webcontainer/registeredComponent.js do not match for the Blog Page component, the component will not show up in the exported website.

2023-05-01 02:08 UTC, Lettuce05 approved these changes
All the export errors have been resolved! Good work, this PR is ready to be merged.

2023-05-01 02:08 UTC, merged