Added Companies tests, fixed bugs, and refactored logo containers
cs472-team6/cs472-team6 pull request #137
Opened 2023-04-19 02:20 UTC by ZacheryEC001

This pull request seeks to address some of the bugs and constructive criticism of the Companies component, including resolving issue #132. 

## Files Changed

**Companies.jsx** 
* Refactored the logo containers to use flex instead of grid, allowing for logos to be centered when items are removed by the user
* Fixed a bug where user-inputted logos would disappear in dark mode
* Removed unused imports

## Files Added

**Companies.test.jsx**
* Added unit tests

## Screenshots
![image](https://user-images.githubusercontent.com/34380051/232949217-7a110e6d-618f-45a5-bf5d-098b50e5405a.png)
_User-inputted logos now work in dark mode_

![image](https://user-images.githubusercontent.com/34380051/232949387-9172268e-263b-42e4-9794-70d8d390a40c.png)
_Thanks to the refactor, logos will now center themselves if the user chooses less than 12 logos_

2023-04-23 08:54 UTC, carruthjhall requested changes
+The responsive styling works as intended, and the component looks good in both light and dark modes.
+The options are able to be edited and the changes are reflected on the screen.
-The options themselves would look better if there was a padding added to the left side using `pl-4` or something around that range.
-Adding the functionality to upload an image rather using an URL might be more suitable. You can find an example of how to do this on the skills component (if it has not been merged, then check PR #126 ). 
-Maybe put the logo options inside of a drop down like the Skills List dropdown here:
![image](https://user-images.githubusercontent.com/85139652/233826768-ad32d4ae-6ffe-410f-97c4-6238323d9e9b.png)
![image](https://user-images.githubusercontent.com/85139652/233826788-d153dff6-b51c-43b4-bc02-4b5fbb846548.png)
This could be done like so: 
`<details>`
`    <summary>Company Logos<summary>`
`         <details>`
`               <summary>Logo {logo #} URL</summary>`
`                   Logo option code goes here `
`         </details>`  
`          ...repeat for rest of logos` 
`</details>`

Able to get coverage on all but 2 of the files. You can use the test file provided by the Banner component to get the coverage you need for CompaniesOptions.jsx.
![image](https://user-images.githubusercontent.com/85139652/233829855-f7e515d1-7475-4c5a-b004-c01435981ed0.png)

Overall good work, just a couple more fixes and this component will be perfect

2023-04-24 18:08 UTC, Lettuce05 commented
Had to close and reopen pull request in order to run GitHub action. Action would not run on preexisting pull requests.

2023-04-26 13:44 UTC, ZacheryEC001 commented
> +The responsive styling works as intended, and the component looks good in both light and dark modes. +The options are able to be edited and the changes are reflected on the screen. -The options themselves would look better if there was a padding added to the left side using `pl-4` or something around that range. -Adding the functionality to upload an image rather using an URL might be more suitable. You can find an example of how to do this on the skills component (if it has not been merged, then check PR #126 ). -Maybe put the logo options inside of a drop down like the Skills List dropdown here: ![image](https://user-images.githubusercontent.com/85139652/233826768-ad32d4ae-6ffe-410f-97c4-6238323d9e9b.png) ![image](https://user-images.githubusercontent.com/85139652/233826788-d153dff6-b51c-43b4-bc02-4b5fbb846548.png) This could be done like so: `<details>` ` <summary>Company Logos<summary>` ` <details>` ` <summary>Logo {logo #} URL</summary>` ` Logo option code goes here` ` </details>` ` ...repeat for rest of logos` `</details>`
> 
> Able to get coverage on all but 2 of the files. You can use the test file provided by the Banner component to get the coverage you need for CompaniesOptions.jsx. ![image](https://user-images.githubusercontent.com/85139652/233829855-f7e515d1-7475-4c5a-b004-c01435981ed0.png)
> 
> Overall good work, just a couple more fixes and this component will be perfect

Thank you for the feedback, I have implemented the requested changes

2023-04-26 21:04 UTC, ebacolod requested changes

2023-04-26 21:04 UTC, ebacolod commented on src/components/Companies/Companies.test.jsx
> +            {url: "/src/components/Companies/Logos/Logo1.svg", darkURL: "/src/components/Companies/Logos/DarkLogo1.svg"},
It was mentioned in Discord that utilizing a file path as the source of your images cannot render in production mode. The solution to this was to host the images on the resources repository (https://github.com/cs472-team6/cs472-team6-resources).

2023-04-27 00:25 UTC, carruthjhall requested changes
Great work! Just some minor changes and this will be ready for merging.

2023-04-27 00:25 UTC, carruthjhall commented on src/components/Companies/CompaniesOptions.jsx
> +            <p className="mt-2 ml-1 text-xs">PNG, JPG, or SVG</p>
Just to make the new dropdowns format nicely, if you want you could do:
summary className: Change `mb-3` to `mb-1`, and add `pl-4`
label, input, and p className: Add `pl-7`

2023-04-27 00:25 UTC, carruthjhall commented on src/components/Companies/Companies.jsx
> +                        })}
Wrap this like
`<details>`
`<summary>Logos</summary>`
`  {logolistarraycomponent} `
`</details>`
to clean it up a bit. But this looks great and the functionality works perfect.

2023-04-27 09:48 UTC, ZacheryEC001 commented on src/components/Companies/CompaniesOptions.jsx
> +            <p className="mt-2 ml-1 text-xs">PNG, JPG, or SVG</p>
Fixed.

2023-04-27 09:48 UTC, ZacheryEC001 commented on src/components/Companies/Companies.jsx
> +                        })}
Fixed.

2023-04-27 09:48 UTC, ZacheryEC001 commented on src/components/Companies/Companies.jsx
> +                <div className="flex align-center justify-center">
Fixed.

2023-04-27 09:50 UTC, ZacheryEC001 commented on src/components/Companies/Companies.test.jsx
> +            {url: "/src/components/Companies/Logos/Logo1.svg", darkURL: "/src/components/Companies/Logos/DarkLogo1.svg"},
@ebacolod At the moment, I do not have write access to that repo. Can you invite me to the organization or merge my PR on that repo? Thank you.

2023-04-28 22:33 UTC, ZacheryEC001 commented on src/components/Companies/Companies.test.jsx
> +            {url: "/src/components/Companies/Logos/Logo1.svg", darkURL: "/src/components/Companies/Logos/DarkLogo1.svg"},
Fixed.

2023-04-29 00:56 UTC, ebacolod approved these changes
Your component looks great! The images look a lot better when centered. I see the source images have been replaced with the URLs from the resource repo. Running in production, the images appear. Well done!

2023-04-29 01:26 UTC, carruthjhall approved these changes
The fixes look great and the component works great. Great work!

2023-04-29 10:35 UTC, merged