Added Blog Page Hero Section component functionality and unit tests
cs472-team6/cs472-team6 pull request #144
Opened 2023-04-25 06:31 UTC by CrystaS15

This pull request aims to resolve issue #140. In this pull request I have created the Blog Page Hero section of the application and all requirements to obtain desired functionality.

# New Features
## BlogPageHeroSection
### Dark Mode
![image](https://user-images.githubusercontent.com/58496136/234186089-7b5ac9c3-8acc-467b-bc84-377cfa8f667d.png)

### Light Mode
![image](https://user-images.githubusercontent.com/58496136/234188783-79860d2f-925f-46ef-885a-b80f39390b14.png)

# Code Changes
### src/components/BlogPageHeroSection/BlogPageHeroSection.jsx
- Added the BlogPageHeroSection component.

### src/components/BlogPageHeroSection/BlogPageHeroSection.test.jsx
- Added tests in order to obtain code coverage of the BlogPageHeroSection component and its corresponding files and functionality.
![image](https://user-images.githubusercontent.com/58496136/234190413-82a6a2a4-574b-497e-80a8-6e9706deecc9.png)

### src/components/BlogPageHeroSection/BlogPageHeroSectionComponent.js
- This is the abstracted version of the components in order to allow a cleaner `registeredComponents.js` file.

### src/components/BlogPageHeroSection/BlogPageHeroSectionOptions.jsx
- Added the BlogPageHeroSection options component.

### src/utils/registeredComponents.js
- A new array element for the BlogPageHeroSection component which will be used to render the appropriate components for the feature of the application.

### UML/BlogPageHeroSectionUML.png
- UML showing the BlogPageHeroSection use case

2023-04-29 22:11 UTC, WuliuQ commented on src/components/BlogPageHeroSection/BlogPageHeroSection.jsx
> +    <div className="flex flex-col items-center justify-center h-screen">
I think you can delete the h-screen in this line to solve component overlapping problem.

2023-04-30 06:14 UTC, CrystaS15 commented on src/components/BlogPageHeroSection/BlogPageHeroSection.jsx
> +    <div className="flex flex-col items-center justify-center h-screen">
I already accounted for the component overlap. I don't see any more issues.

2023-04-30 08:15 UTC, WuliuQ commented on src/components/BlogPageHeroSection/BlogPageHeroSection.jsx
> +    <div className="flex flex-col items-center justify-center h-screen">
![屏幕截图 2023-04-30 011410](https://user-images.githubusercontent.com/94213565/235342941-17f1eaf9-451b-4ddb-a2d8-39c4bfc60434.png)
I don't know if it's my device's problem, but when I try to change to the largest size it will show like this.

2023-04-30 08:19 UTC, WuliuQ approved these changes
The component works fine, change the input can change the component as well, the test is also nice.
![屏幕截图 2023-04-30 011702](https://user-images.githubusercontent.com/94213565/235343077-a79c7836-1de9-41d9-8e71-9e7405ed2d26.png)
The only thing I suggest is make sure the overlapping is resolve.

2023-05-01 00:58 UTC, Lettuce05 requested changes
The same problem addressed before still exists and there is actually an additional problem. The title of the blog page now gets cut off at large screen sizes. See the below images for reference.

![image](https://user-images.githubusercontent.com/61034923/235384901-4df1312b-c89a-46fa-b634-5b73d7279244.png)

![image](https://user-images.githubusercontent.com/61034923/235384978-37642c16-6415-4110-b43b-7740d9c4df83.png)

2023-05-01 01:13 UTC, CrystaS15 commented on src/components/BlogPageHeroSection/BlogPageHeroSection.jsx
> +    <div className="flex flex-col items-center justify-center h-screen">
I think you were right, thank you for letting me know.

2023-05-01 01:42 UTC, Lettuce05 approved these changes
Great work! As seen in the images below the previous problems have been resolved.

![image](https://user-images.githubusercontent.com/61034923/235388679-b8ba1c28-7892-478c-9249-b3a3c3901669.png)

![image](https://user-images.githubusercontent.com/61034923/235388694-18caf1f2-0e23-47df-ae6b-27132b0f0b05.png)

All tests pass and full code coverage is provided by unit test.

![image](https://user-images.githubusercontent.com/61034923/235388818-34df698a-e095-40fb-b200-838ede3a82a9.png)

![image](https://user-images.githubusercontent.com/61034923/235388885-e615b596-0afe-4a26-bf7e-7cc7a40c53e2.png)

2023-05-01 01:42 UTC, merged