Added Testimonial Section
cs472-team6/cs472-team6 pull request #151
Opened 2023-04-26 14:38 UTC by ZacheryEC001

This PR aims to close the issue #138 by implementing the Testimonial Section.

## Files Changed
**Testimonial.jsx**
* Fixed a console error bug relating to array children not having keys

**registeredComponents.js**
* Added testimonial section component to list of registered components

## Files Added

**TestimonialSection.jsx**
* Implements the testimonial section

**TestimonialSectionOptions.jsx**
* Implements the options input for the testimonial section

**TestimonialSection.test.jsx**
* Implements tests for the testimonial section

**TestimonialSectionComponent.jsx**
* Implements PageComponent instance of the testimonial section

**TestimonialSectionLight.png**
* Image showing preview of the component

**TestimonialSectionUML.png**
* Image with the UML diagram describing the structure of the component

## Screenshots
### Light Mode

![image](https://user-images.githubusercontent.com/34380051/234610120-1caf9176-781e-4203-8f3d-0be276de2067.png)

### Dark Mode

![image](https://user-images.githubusercontent.com/34380051/234610285-379a719d-ede5-4922-ae01-b70fd99709e4.png)

2023-04-27 06:43 UTC, ebacolod requested changes

2023-04-27 06:43 UTC, ebacolod commented on src/utils/registeredComponents.js
>      ['Testimonial', TestimonialComponent],
I think you can take the Testimonial entry out of the registered components list since the Testimonial Section serves the purpose of the original Testimonial.

2023-04-27 06:43 UTC, ebacolod commented on src/components/Testimonial/Testimonial.jsx
>          <div className="flex flex-col items-start p-8 bg-white dark:bg-gray-900 h-fit  md:w-[436.58px] m-4">
Instead of using `bg-white` as the background color of the testimonial, I think using the Figma file's primary white color, `bg-[#F0F2F5]`, makes it look better.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/58874823/234773908-77eb3957-a29f-4950-8878-693650a68d7c.png">

2023-04-27 06:43 UTC, ebacolod commented on src/components/TestimonialSection/TestimonialSectionLight.png
On my laptop screen, this image takes up a lot of screen real estate
<img width="215" alt="image" src="https://user-images.githubusercontent.com/58874823/234774614-51526193-4799-4a08-b7e3-6e0e4f678d58.png">

If you crop it to only the top four testimonials, you can see more from the other components and pick out more details from the testimonial section. If you wanted to, I believe you can change the default noOfTestimonials to 4 in TestimonialSectionOptions.jsx so that it matches the preview.

Also, the preview image has a little orange border around it from clicking the Figma file. It can even be seen in the preview as shown above. If you crop out the border, it'll look a little bit cleaner. 

Lastly, I briefly mentioned this in another comment, but if you change the star colors to black and white, it'd be better to take a screenshot of the rendering and use that as the preview. This is so that there is no confusion between the preview and the actual component

2023-04-27 07:33 UTC, ZacheryEC001 commented on src/components/TestimonialSection/TestimonialSection.jsx
> +            <h2 className="text-main font-bold text-[32px] md:text-[64px] mt-11 mb-11 dark:text-[#F0F2F5] flex justify-center">Client &#20;<span className={`text-transparent bg-clip-text bg-gradient-
The ```&#20;``` tag displays as a normal space on my machine, so I appreciate the insight. Fixed.

2023-04-27 07:37 UTC, ZacheryEC001 commented on src/components/Testimonial/Testimonial.jsx
>          <div className="flex flex-col items-start p-8 bg-white dark:bg-gray-900 h-fit  md:w-[436.58px] m-4">
Fixed.

2023-04-27 09:16 UTC, ZacheryEC001 commented on src/components/TestimonialSection/TestimonialSectionOptions.jsx
> +            <details className="bg-white mx-1 rounded-lg" open>
Thank you for the feedback. This has definitely been on my radar and I have come up with an alternate solution. Now, when you change the gradient of the header, the stars change color to the first color of the gradient to give the user additional customization options while making the stars pop.

![image](https://user-images.githubusercontent.com/34380051/234817354-34399eff-d86e-403c-8363-55509a68e0d3.png)

Fixed.

2023-04-27 09:32 UTC, ZacheryEC001 commented on src/utils/registeredComponents.js
>      ['Testimonial', TestimonialComponent],
Removed.

2023-04-28 21:59 UTC, ebacolod approved these changes
Thanks for implementing all the changes! They work very well. The star colors look really good. Nice Work!

2023-04-29 16:40 UTC, WuliuQ approved these changes
The code works fine, every input can change the component, the responsiveness also works fine. The test coverage is good:
![屏幕截图 2023-04-29 093940](https://user-images.githubusercontent.com/94213565/235313834-035c2a15-a4e6-432d-bc80-4c5e662e8adc.png)

2023-04-29 18:17 UTC, merged