#142 Trusted Companies Component
cs472-team6/cs472-team6 pull request #157
Opened 2023-04-27 20:01 UTC by alexfox361

This PR attempts to solve issue #142. To do this, I added a new Trusted Companies Component. 

This component allows for the user to display a custom string and custom amount of images. 

I also added tests for this component. These test validate the input and rendering of the component's features. 

## Custom Fields
- Title
- Number of Companies
- Company Name
- Company Image

## Preview of Component 
<img width="843" alt="image" src="https://user-images.githubusercontent.com/71406323/234976843-d9eac69d-97d1-456b-ac2b-556916be11d8.png">

## Files Changed

src/components/TrustedCompanies/TrustedCompanies.jsx:
- Added the design of the component. 

src/components/TrustedCompanies/TrustedCompanies.test.jsx:
- Tested the component for validation of input and rendering. 

src/components/TrustedCompanies/TrustedCompaniesComponent.js:
- Added the default options and rendering of the component. 

src/components/TrustedCompanies/TrustedCompaniesOptions.jsx:
- Added the customizable options of the component. 

src/components/TrustedCompanies/TrustedCompaniesPreview.png:
- Added a Preview of the component. 

src/utils/registeredComponents.js: 
- Added the component to the list of registered components.

2023-04-29 19:48 UTC, CruzG-Dylan requested changes
The component does seem to function as intended and the component does scale well with different screen sizes. Modifying the amount of companies using the add and delete buttons work, and the file upload and image urls change the component as intended. 

It does seem that the individual company titles aren't able to be changed even though there is an option to modify it in the tab. I would suggest either removing the option to change the title in general or updating it to match the intended use.

2023-04-29 23:36 UTC, alexfox361 commented
Thanks @CruzG-Dylan, I didn't notice that in testing. The bug should be fixed now.

2023-04-30 01:35 UTC, CruzG-Dylan approved these changes
Everything looks good now. Nice work.

2023-04-30 05:32 UTC, ebacolod requested changes
Testing, responsiveness, and inputs work well. However, one problem with the rendering is that when you add multiple components, the logos goe off the screen. 

<img width="958" alt="image" src="https://user-images.githubusercontent.com/58874823/235337164-e3cd8fb4-6238-4770-a504-a48b8c333b12.png">

Also, the 3rd company logo is missing some text. Zach has uploaded on the resources repo several logos that were used in the other Companies component. Here's the link: https://github.com/cs472-team6/cs472-team6-resources/tree/main/images/CompanyLogos. I believe the specific file is `DarkLogo4.svg`

2023-04-30 06:49 UTC, alexfox361 commented
Thanks @ebacolod, I made the changes and it should hopefully look better now.

2023-04-30 07:16 UTC, ebacolod requested changes

2023-04-30 07:16 UTC, ebacolod commented on src/components/TrustedCompanies/TrustedCompanies.jsx
> +        <img src={Picture} alt={Name} className="max-w-[130px] object-contain max-h-[130px] my-[20px] md:my-[60px] mr-[40px]"/>
When going in between screen sizes, the vertical margins between images are pretty large. 

<img width="586" alt="image" src="https://user-images.githubusercontent.com/58874823/235340726-6173995e-664b-4765-83ee-d39bfe49e58f.png">


I think if you lower the value of `md:my-[60px]`, it'll look much better. But also, this margin affects the spacing between other components, so make sure that it looks good in between components too.

2023-04-30 07:21 UTC, alexfox361 commented on src/components/TrustedCompanies/TrustedCompanies.jsx
> +        <img src={Picture} alt={Name} className="max-w-[130px] object-contain max-h-[130px] my-[20px] md:my-[60px] mr-[40px]"/>
Okay I lowered it to 20px. Let me know what you think.

2023-04-30 07:28 UTC, ebacolod approved these changes
LGTM!

2023-04-30 17:19 UTC, merged