Added support for all gradients for the testimonial stars
cs472-team6/cs472-team6 pull request #165
Opened 2023-04-30 00:24 UTC by ZacheryEC001

This PR seeks to close the issue #164 by adding all of the colors in the getColorFromGradient switch statement.

## Files Changed

### **Testimonial.jsx**
* Added additional colors to getColorFromGradient

## Screenshots

![image](https://user-images.githubusercontent.com/34380051/235329617-6bc1de3e-430a-44df-8dc4-8b03d9aaccf2.png)
_Stars now match color for all gradients_

2023-04-30 08:38 UTC, ebacolod requested changes

2023-04-30 08:38 UTC, ebacolod commented on src/components/Testimonial/Testimonial.jsx
>      switch(colorName){
I really like the different gradients available to us, but all these cases have decreased our branch coverage by ~16%. Whenever I did the demo for the prototype, it had 87% branch coverage, but now it is at 71%.  

### Demo-Prototype Build
<img width="551" alt="image" src="https://user-images.githubusercontent.com/58874823/235343469-605b93f1-fb1b-4972-90c3-cfde53cd11fa.png">

### Gradient Build
<img width="551" alt="image" src="https://user-images.githubusercontent.com/58874823/235343504-97d613b9-bd2a-4327-850c-92af6ca8f8fa.png">


According to the professor's evaluation, at least 85% branch coverage is needed to get the max points on tests: https://docs.google.com/document/d/1AhUVxWgfDtQVmgEJD0acVPnD72SRoKTHJ2Qh5X6IPqY/edit#. (*Note: This may not be entirely accurate, but this is the only thing we have to go off of.*)

A lot of the missing coverage comes from three files:
- ContactSection.jsx
  - <img width="608" alt="image" src="https://user-images.githubusercontent.com/58874823/235343533-5cdcf040-3eb8-4616-a3ab-8b16247cc493.png">
- CtaSection.jsx
  - <img width="552" alt="image" src="https://user-images.githubusercontent.com/58874823/235343545-9f6cf27b-9b30-4a94-9e91-92cdcc199b74.png">
- Testimonial.jsx
  - <img width="551" alt="image" src="https://user-images.githubusercontent.com/58874823/235343640-3b034ca7-4864-4664-81d2-c65b9bf309d3.png">

My suggestion to increase coverage would be to place the getColorFromGradient() function in a separate file. Then, you would write tests for that file. Each of the 3 files would have to import that function to call it.

I'm not entirely sure that this is the correct way to do testing. Either Anthony or Alex may be able to help. Remember, if-else and switch statements are what increases the number of branches.

2023-04-30 17:50 UTC, WuliuQ commented on src/components/Testimonial/Testimonial.jsx
>      switch(colorName){
I already make the test for the CtaSection.jsx, so you just need to make the other two.
![屏幕截图 2023-04-30 105013](https://user-images.githubusercontent.com/94213565/235368349-8bb77eba-552f-406e-8d4f-86bd9df1806d.png)

2023-05-01 00:30 UTC, ZacheryEC001 commented
Fixed. The test coverage for branches is now 83.73%, and will increase further when the test @WuliuQ implemented in his PR #130

2023-05-01 01:17 UTC, ebacolod requested changes

2023-05-01 01:17 UTC, ebacolod commented on src/components/Testimonial/Testimonial.jsx
> +    console.log(choppedGrad);
Make sure to remove console.log() lines so that the console doesn't clutter up.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/58874823/235387099-645561ae-0e7c-4684-8cc5-b052a625c5e3.png">

2023-05-01 01:17 UTC, ebacolod commented on src/components/ContactSection/contactSection.test.jsx
> +            console.log(contactJSON.children[0].children[3].children[0].children[0].children[1].children[0].children[0]);
They also appear in your testing too.

2023-05-01 01:17 UTC, ebacolod commented on src/components/Testimonial/Testimonial.test.jsx
> +        console.log(stopColor);
Here as well. 3 in this file.

2023-05-01 02:34 UTC, WuliuQ approved these changes
The color can change when I change the input, the test coverage is also increase. Just make sure delete the consle.log() like [ebacolod](https://github.com/ebacolod) said.
![屏幕截图 2023-04-30 193303](https://user-images.githubusercontent.com/94213565/235393571-0289465c-05da-414d-91db-001c5c5e5eac.png)

2023-05-01 04:29 UTC, ZacheryEC001 commented
Fixed.

2023-05-01 04:55 UTC, ebacolod requested changes
I just merged Carruth's PR and it had updates to the FAQ + ContactSecton. There's going to be a merge conflict in the contactSection.test.jsx file. Resolve the conflict and double-check the test coverage as well.

2023-05-01 05:08 UTC, ZacheryEC001 commented
> I just merged Carruth's PR and it had updates to the FAQ + ContactSecton. There's going to be a merge conflict in the contactSection.test.jsx file. Resolve the conflict and double-check the test coverage as well.

Just fixed the merge conflicts now, with these results for the coverage:

![image](https://user-images.githubusercontent.com/34380051/235409452-0ebbd8aa-1886-4f00-836f-ebd853db61af.png)
Total test coverage

![image](https://user-images.githubusercontent.com/34380051/235409514-0f8fa065-5b70-4744-adf7-8dff3f1e6867.png)
Test coverage for contact section

2023-05-01 05:17 UTC, ebacolod requested changes
I'm getting this error when trying to run on StackBlitz and locally on my machine

<img width="425" alt="image" src="https://user-images.githubusercontent.com/58874823/235410157-335b40b5-b891-4309-84ba-9b31820b0c74.png">

<img width="666" alt="image" src="https://user-images.githubusercontent.com/58874823/235410222-b24e905c-5986-4645-9812-c5d715b94c53.png">

2023-05-01 05:22 UTC, ZacheryEC001 commented
> I'm getting this error when trying to run on StackBlitz and locally on my machine
> 
> <img alt="image" width="425" src="https://user-images.githubusercontent.com/58874823/235410157-335b40b5-b891-4309-84ba-9b31820b0c74.png">
> 
> <img alt="image" width="666" src="https://user-images.githubusercontent.com/58874823/235410222-b24e905c-5986-4645-9812-c5d715b94c53.png">

This is due to the fact that

> I'm getting this error when trying to run on StackBlitz and locally on my machine
> 
> <img alt="image" width="425" src="https://user-images.githubusercontent.com/58874823/235410157-335b40b5-b891-4309-84ba-9b31820b0c74.png">
> 
> <img alt="image" width="666" src="https://user-images.githubusercontent.com/58874823/235410222-b24e905c-5986-4645-9812-c5d715b94c53.png">

This is because a previous PR removed that file, but the reference in filesystem.js remained. Nonetheless, fixed.

2023-05-01 05:30 UTC, ebacolod commented on webcontainer/registeredComponents.js
> +<<<<<<< HEAD
Does this cause a problem? I'm not entirely sure. I've tested everything and it seems fine, but I don't know if this will be an issue.

2023-05-01 05:32 UTC, ZacheryEC001 commented on webcontainer/registeredComponents.js
> +<<<<<<< HEAD
Looks like a merge conflict snuck in there, I fixed it

2023-05-01 06:14 UTC, ebacolod approved these changes
Nice Work! I rechecked inputs, testing, responsiveness, imports/exports, and light/dark mode. It looks great. The new gradients are a nice feature.

2023-05-01 06:16 UTC, merged