Adding Footer component and updating registeredComponents file
cs472-team6/cs472-team6 pull request #64
Opened 2023-03-10 23:02 UTC by arroya2

I added a new folder called Footer with three files in it. The first file is the Footer.jsx that will take some arguments and create the footer component. The second file is the FooterOptions.jsx, that is where you can update link locations on the PageOptionsTab. Lastly, the third file is just an image used for previewing the component. And also updated the array to add my footer component into the registeredComponents.js file

2023-03-21 22:35 UTC, WuliuQ reviewed
I think you need to import your files in registeredComponents.js first, and also make your Footer component folder in the components folder, not just add the Footer after the components folder.

2023-03-22 04:19 UTC, Lettuce05 commented
[![Open in Codeflow](https://developer.stackblitz.com/img/open_in_codeflow.svg)](https://pr.new/github.com/cs472-team6/cs472-team6/pull/64)

2023-03-22 04:59 UTC, CrystaS15 reviewed
Your component, options, and preview should be in their own Footer folder in the components folder. Your registeredComponents.js should also have imported files as well. When I ran the code, I just saw a blank page with no working features.

2023-03-23 22:44 UTC, ZacheryEC001 requested changes
Please reference my comment on registeredComponents.js to get your code to work.

2023-03-23 22:44 UTC, ZacheryEC001 commented on src/utils/registeredComponents.js
In order for the code to work, you must import Footer, FooterOptions, and FooterPreview as you mention them in the code but never define them, giving a ReferenceError: 'Footer' is not defined.

2023-03-24 15:44 UTC, closed without merging