Added Contact Section Component
cs472-team6/cs472-team6 pull request #72
Opened 2023-03-16 10:11 UTC by carruthjhall

This pull request aims to resolve issue #54. In this pull request I have added the ContactSection Component and the ContactSectionOptions component.

### **New Features** 
__________

- ContactSection Component
  - This component allows the user to add a section for a user to contact the owner of the portfolio. The user would use the provided form inputs to contact the owner.
- ContactSectionOptions Component
  - This component allows the user to edit the header and description as well as add their email and phone number to the section.

## **Screenshots of New Features**
## Dark Mode
![image](https://user-images.githubusercontent.com/85139652/225579755-80a90fd5-3945-486a-9cc6-a8a69ee28f15.png)

## Light Mode
![image](https://user-images.githubusercontent.com/85139652/225580059-d75f1b5e-04af-4a52-9a55-040345728513.png)

## User Input Form Test
![image](https://user-images.githubusercontent.com/85139652/225580852-17f48669-1b29-4d39-aeaf-041c1225026b.png)

## ContactSectionOptions Test(The user can use the options panel to customize their header, etc.)
![image](https://user-images.githubusercontent.com/85139652/225581306-e27d34b3-4c00-4e50-b42f-99e85b21a7aa.png)

## Code Changes

**ContactSection.jsx**
- Added the ContactSection component (function used to render this section in the render panel)

**ContactSectionOptions.jsx**
- Added the ContactSectionOptions component (function used to render the options in the options panel)

**ContactSectionPreview.png**
- Added the ContactSectionPreview to display to the user what the component looks like in the options panel.

**registeredComponents.js**
- Added the ContactSection component to the registeredComponents array so that it is available in the UI

**tailwind.config.cjs**
- Added two colors(grayblack, graywhite) to the theme:extend:colors module for the input text field backgrounds

**miniDollarIcon.svg, miniDollarIcon.svg, phoneIcon.svg, blackMiniDollarSign.svg, blackMiniEmail.svg**
- Added .svg files to the components/ContactSection/ folder used for the icons used in the contact section.

2023-03-22 04:16 UTC, Lettuce05 commented
[![Open in Codeflow](https://developer.stackblitz.com/img/open_in_codeflow.svg)](https://pr.new/github.com/cs472-team6/cs472-team6/pull/72)

2023-03-22 04:47 UTC, CrystaS15 approved these changes
I ran the code and saw that it meets the desired functionality and meets requirements. One small issue that I suggest that you look into is that once you get through the errors for the email and submit, I noticed that re-submitting another form did not re-generate the errors and even allowed me to enter a completely empty form.

2023-03-22 07:48 UTC, ebacolod commented
Your color themes for light mode and dark mode are swapped. Head into ContactSection.jsx to swap the two themes.

2023-03-23 22:58 UTC, ZacheryEC001 commented on src/components/ContactSection/ContactSection.jsx
I would create an option to choose the gradient on the text and button instead of hard coding the values for gradient 1. An example of this can be found on the Banner component.

2023-03-23 22:59 UTC, ZacheryEC001 requested changes
The code works on my end and the component looks good. I would recommend making responsive styling for smaller screen sizes. In the Figma file, the design takes the forms and puts them underneath the text like so:

![image](https://user-images.githubusercontent.com/34380051/227382260-52546275-4328-490b-bec5-0460fe66717a.png)

Additionally, I would use the gradients we have in the utils.js to increase user control over their portfolio. See the comment on the ContactSection.jsx file for more info.

2023-03-27 10:01 UTC, closed without merging