Added Testimonial component
cs472-team6/cs472-team6 pull request #80
Opened 2023-03-21 22:48 UTC by ZacheryEC001

This pull request aims to resolve issue #56 by implementing the testimonial component and it's options. Everything from that issue is addressed by this pull request, with the exception of the starGradient option. Tailwind does not seem to support directly filling SVGs with gradients, so for the sake of time I will address this concern in a future pull request. I have opened up issue #79 as a result.

## Files Added

**Testimonial.jsx** 
* Implemented the Testimonial component

**TestimonialOptions.jsx**
* Implemented the TestimonialOptions

**TestimonialPreviewLight.png**
* Preview for the Testimonial component which shows in the ComponentListTab

**star.svg**
* SVG file for the stars in the testimonial

## Files Modified

**registeredComponents.js** 
* Added testimonial component to the registered components list

## Screenshots

**Light Mode**
![image](https://user-images.githubusercontent.com/34380051/226754305-a9296264-8fc6-4dfa-a805-325abb933ca1.png)

**Dark Mode**
![image](https://user-images.githubusercontent.com/34380051/226754424-8bc44d22-2d3b-456d-8693-f54b94e4c061.png)

2023-03-22 03:49 UTC, Lettuce05 requested changes
Everything looks great with the code and it functionally works when changing the options in the UI. The only fix that I would recommend is that the component itself is not responsive. When I make the screen skinnier the component should adapt so that the content fits on the page rather than being pushed off the screen. My suggestion would be to set the width of the component to 80% or 90% for small screen sizes and then keep your current styling for larger screen sizes.

2023-03-22 04:11 UTC, Lettuce05 commented
[![Open in Codeflow](https://developer.stackblitz.com/img/open_in_codeflow.svg)](https://pr.new/github.com/cs472-team6/cs472-team6/pull/80)

2023-03-28 21:04 UTC, ebacolod requested changes
The testimonial component takes up the whole width of the rendering page when at 2xl screen sizes. 
![image](https://user-images.githubusercontent.com/58874823/228361771-1096697d-6aa3-48b4-9a68-fdfd1db0f7ef.png)

This link explains how tailwind does its responsive design:
https://tailwindcss.com/docs/responsive-design#working-mobile-first

Also, I suggest looking at the Service Wrapper component to see how the sizing is done. (Specifically in the ServiceWrapper.jsx file).

Once you're ready, go ahead and make changes to Testimonial.jsx.

2023-03-28 21:47 UTC, ZacheryEC001 commented
> The testimonial component takes up the whole width of the rendering page when at 2xl screen sizes. ![image](https://user-images.githubusercontent.com/58874823/228361771-1096697d-6aa3-48b4-9a68-fdfd1db0f7ef.png)
> 
> This link explains how tailwind does its responsive design: https://tailwindcss.com/docs/responsive-design#working-mobile-first
> 
> Also, I suggest looking at the Service Wrapper component to see how the sizing is done. (Specifically in the ServiceWrapper.jsx file).
> 
> Once you're ready, go ahead and make changes to Testimonial.jsx.

Fixed

2023-03-28 22:10 UTC, ebacolod approved these changes
2xl bug is fixed. Good Work!

2023-03-29 00:17 UTC, Lettuce05 requested changes

2023-03-29 00:17 UTC, Lettuce05 commented on src/utils/registeredComponents.js
> +    ['Testimonial', TestimonialComponent]
Missing comma which is causing a syntax error for the application.

2023-03-29 01:11 UTC, Lettuce05 approved these changes
The component now works great at all sizes. As can be seen by the images below for each of the screen sizes. This pull request is good to be merged. No functionality has broken as I can still dynamically update the options of the component (this can be seen in the images as well).

### Large Screen (Desktop)
![image](https://user-images.githubusercontent.com/61034923/228400343-ff98bea9-9f00-4377-8ad2-7e5719295d85.png)

### Medium Screen (Tablet)

![image](https://user-images.githubusercontent.com/61034923/228400382-a17a7f37-b18e-43f4-b706-dd707cdd9177.png)

### Small Screen (Phone)

![image](https://user-images.githubusercontent.com/61034923/228400453-aef24d8e-36be-4a3c-afe3-06b1d8e1e940.png)

2023-03-29 01:11 UTC, merged