Added FAQ Section component
cs472-team6/cs472-team6 pull request #82
Opened 2023-03-23 09:56 UTC by carruthjhall

This pull request aims to resolve issue #73. In this PR I have added the faqSection component and the faqSectionOptions component, as well as a supplemental file used in the faqSection component.

### **New Features**
____
- faqSection Component
  - This component allows the user to add a Frequently Asked Questions section so that the portfolio owner can answer any common questions a viewer may have.
- faqSectionOptions
  - This component adds the option functionality for the user to modify the questions and answers for the FAQ section.

### **Screenshots of New Features**
___

### Dark Mode
___
![image](https://user-images.githubusercontent.com/85139652/227164759-94e65d1e-8afd-4713-879e-908aa6da6ad0.png)

### Light Mode
___
![image](https://user-images.githubusercontent.com/85139652/227164645-8bfe5c88-9003-4715-9da5-f4f1a0c617c4.png)

### Modified Questions & Accordion example
___
![image](https://user-images.githubusercontent.com/85139652/227165457-70c78430-d79a-472f-8f45-8eedd05dc979.png)

![image](https://user-images.githubusercontent.com/85139652/227165623-f1c82c39-e1c8-4919-800f-205f23d24d44.png)

### **Code Changes**
____
- faqSection.jsx
  - This file returns the code that renders the FAQ section.
- faqSectionOptions.jsx
  - This file returns the code that renders the options that modifies the questions/answers for the FAQ section
- Accordion.jsx
  - This file is used to create the accordion that lists the questions/answers the portfolio creator adds. The array in the faqSection.jsx uses this function to iterate and display the Q/A's as an accordion.   
- darkDropArrow.svg, darkDropArrowReverse.svg, lightDropArrow.svg, and lightdropArrowReverse.svg
  - These are the svg files that render the arrows on the accordion, depending to the user's color scheme.
- registeredComponents.js
  -  Added the faqSection component to the array of components.

2023-03-23 19:22 UTC, CruzG-Dylan requested changes
The component does seem to function as intended, and modifying it in the options tab presents no major bugs. However, I would suggest that there should be an option to also modify the flavor text and Contact Me button link.

2023-03-28 08:03 UTC, CrystaS15 approved these changes
I do not see any issues with the code. I can see the fields in the `faqComponent.js` file cleans up the `registeredComponents.js` file.

I ran the code and I see that the flavor text is now modifiable, and the functionalities all work as intended. The gradient works well and the light and dark modes work as intended.

2023-03-28 20:58 UTC, CruzG-Dylan approved these changes

2023-03-28 21:39 UTC, arroya2 approved these changes
This component works as intended with no noticeable bugs

2023-03-28 21:39 UTC, merged