Added Sm(Social Media) Component
cs472-team6/cs472-team6 pull request #83
Opened 2023-03-23 17:14 UTC by CruzG-Dylan

This pull request aims to resolve issue #61. The Social Media component allows users to link their profiles to the corresponding social media icons.

New Feature
======

- Sm (Social Media) Component
  - This component allows users to modify the following:
     - Title
     - Body
     - Background Image
     - Embedded hyperlink in the corresponding social media icons

Screenshots of New Features
======
### Social Media (Light Mode)
![image](https://user-images.githubusercontent.com/123264985/227276996-b5be30dd-ebc7-44bb-b523-887e0984e4f8.png)
======
### Social Media (Dark Mode)
![image](https://user-images.githubusercontent.com/123264985/227277237-c3a602be-7795-4ebb-96fd-dca7b3deddb1.png)

New Feature
======
### Sm.jsx
- Added base implementation of social media component 
### SmOptions.jsx
-  Added social media option component to allow users to modify it
### SmPreview.png
- Added image preview for the ComponentsListTab
### registeredComponents.js
- Added Social Media component to the registered components list

2023-03-25 04:48 UTC, alexfox361 requested changes
Hey @CruzG-Dylan, nice work so far. There is a few issues. Firstly, this component does not have any logic for different screen sizes. When the screen changes sizes (sm, md, lg) the component should change in order to match the design on Figma.

Here's a link that explains Tailwind's built in utility for this:
https://tailwindcss.com/docs/responsive-design

Next, I think it would be nice if there were some logic to allow for some of the links to not be displayed. I don't think that everyone will have all social media accounts. 

Lastly, Sm is a confusing name. I would recommend changing that to something like "Social Media". 

Let me know if you have any questions.

2023-03-28 22:39 UTC, ebacolod requested changes
The only issue is with the React import in SocialMedia.jsx. Take a look at my comment about it. Everything else, however, is really good.

2023-03-28 22:39 UTC, ebacolod commented on src/components/SocialMedia/SocialMedia.jsx
> +import React, {useState} from "React"
When trying to run your code on StackBlitz, I get this following error message.

![image](https://user-images.githubusercontent.com/58874823/228380556-55e6afab-2c6d-439d-8275-bbf8288817b1.png)

I believe the issue is due to this import. "React" needs to be lowercase "react". Furthermore, I don't think you need this import at all, since it is not utilized in your code.  

Otherwise, the responsive design works really and looks good on different screen sizes.

2023-03-29 01:26 UTC, ebacolod requested changes
I'm able to get your code running now. The functionality of your code works really well. UML diagram looks good too. However, there's no code coverage on your SocialMediaOptions.jsx file.

![image](https://user-images.githubusercontent.com/58874823/228401483-3f17bda3-dbd2-466f-b667-e0597e8c5606.png)


Look at the tests pushed onto the main branch such as the Banner component and the EducationAndWork component.  You need to render an <OptionsComponent ... /> component to do the testing as seen below

![image](https://user-images.githubusercontent.com/58874823/228402284-7d4ac832-b945-4441-aa17-4509bee7fbdd.png)

Try to get above 85% coverage overall. You can get coverage by doing `npm run coverage`

2023-03-29 03:21 UTC, CruzG-Dylan commented
I was able to add coverage for the SocialMediaOptions.jsx file and improved the overall coverage for the component.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/123264985/228417493-26db7b38-5f10-440c-bf8b-af87f9eefa0c.png">

2023-03-29 03:23 UTC, ebacolod approved these changes
Awesome work! I was able to get nearly full code coverage on my end

![image](https://user-images.githubusercontent.com/58874823/228418493-387b3bf8-3f70-4afe-888b-ccf5500667e2.png)

Everything else from before still works so I approve this PR

2023-03-29 04:01 UTC, carruthjhall approved these changes
Hey, @CruzG-Dylan,

The UML design looks good.

The component follows the correct syntax for the registeredComponents array.

The component renders correctly and follows the responsive styling formats for each screen size.

The component options work as intended.

2023-03-29 05:47 UTC, alexfox361 approved these changes
This PR seems to look good. There has been some responsiveness added, but could still use some work. It looks like when the screen hits a certain size it no longer keeps its design. I think that this isn't too big of an issue and shouldn't prevent it from being merged. 

Nice work!

2023-03-29 05:47 UTC, merged