#86 Side Bar Bug
cs472-team6/cs472-team6 pull request #87
Opened 2023-03-24 00:02 UTC by alexfox361

This pull request attempts to fix the issue of the sidebar not properly toggling. The issue can be seen in this ticket #86. 

To fix this issue I created a conditional statement that first checks if it is in Dev View. Once Dev View is determined, it will decide the width or visibility based of of the isVisible conditional. 

### Images of Fixed Sidebar

**Nothing Hidden**
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/71406323/227390109-a5fbdfe6-d24e-43c8-b4bf-2cb8f5d70f07.png">

**Dev View**
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/71406323/227390122-8a271eb5-e154-4d83-bdb4-226eb2a18cbb.png">

**Hidden Sidebar**
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/71406323/227390148-a9a968b7-cb72-4aff-b4b9-52a863d8437f.png">

2023-03-24 06:59 UTC, ebacolod requested changes
When clicking dev view, the tabs are still visible and can be hover-overed. 

![image](https://user-images.githubusercontent.com/58874823/227431342-38a6fd86-e900-47e2-8623-2cf2f49ab67f.png)

I think replacing the TabButtion() function in SidePanel.jsx with the code below will resolve the issue and make it cleaner. See if this works and play around with it to see if you want to change anything.
```
function TabButton({icon, selected, selectTab}) {
    let setVisibility = SidePanelVisibility((state) => state.setVisibility);
    let isDevView = devViewState((state) => state.isDevView);

    return (
        <button 
            className={`py-2 ${selected ? 'bg-gray-400' : 'hover:bg-gray-300'} ${isDevView ? "px-0 w-0" : "px-3 w-12 " } duration-500`}
            onClick={() => {
                selectTab();
                setVisibility(true);
            }} 
        >
            <div className={`${isDevView ? "invisible" : "visible" }`} > <Icon name={icon} /> </div>
        </button>
    )
}
```

2023-03-24 20:03 UTC, alexfox361 commented
> When clicking dev view, the tabs are still visible and can be hover-overed.
> 
> ![image](https://user-images.githubusercontent.com/58874823/227431342-38a6fd86-e900-47e2-8623-2cf2f49ab67f.png)
> 
> I think replacing the TabButtion() function in SidePanel.jsx with the code below will resolve the issue and make it cleaner. See if this works and play around with it to see if you want to change anything.
> 
> ```
> function TabButton({icon, selected, selectTab}) {
>     let setVisibility = SidePanelVisibility((state) => state.setVisibility);
>     let isDevView = devViewState((state) => state.isDevView);
> 
>     return (
>         <button 
>             className={`py-2 ${selected ? 'bg-gray-400' : 'hover:bg-gray-300'} ${isDevView ? "px-0 w-0" : "px-3 w-12 " } duration-500`}
>             onClick={() => {
>                 selectTab();
>                 setVisibility(true);
>             }} 
>         >
>             <div className={`${isDevView ? "invisible" : "visible" }`} > <Icon name={icon} /> </div>
>         </button>
>     )
> }
> ```

Thanks @ebacolod, this issue should be fixed now.

2023-03-24 23:50 UTC, ebacolod approved these changes

2023-03-28 06:26 UTC, Lettuce05 approved these changes
The code changes seem to fix the sidebar/devview bug. As seen in the image below the sidebar logos are no longer seen when in devview. The code changes provide a simple and clean solution to fixing the bug.

![image](https://user-images.githubusercontent.com/61034923/228146058-3867d74a-7b54-48c1-a3c0-c4525eb1a64c.png)

If there was one suggestion I could make it would be to somehow change the status of the "Dev View" button when in or not in Dev Mode. Whether this means changing the color depending on the mode or slightly changing the text, just to provide something to differentiate which mode the developer is in.

Great Job!

2023-03-28 06:26 UTC, merged